name: Autocloser
on: [issues, pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues and PRs
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "🚀 Development has moved, please open issues at https://github.com/python-humanize/humanize/issues 🚀"
        pr-close-message: "🚀 Development has moved, please open PRs at https://github.com/python-humanize/humanize/pulls 🚀"
        issue-pattern: "🚀🚀🚀 Development has moved to https://github.com/python-humanize/humanize 🚀🚀🚀"
        pr-pattern: "🚀🚀🚀 Development has moved to https://github.com/python-humanize/humanize 🚀🚀🚀"
